- it is possible to edit data of another mod or H3 data via mods - mods can access only ID's from dependenies, virtual "core" mod and itself (optional for some mods compatibility) - metadata field for JsonNode, used to track source mod - moved wog creatures into wog mod - (linux) convertMP3 option for vcmibuilder for systems where SDL_Mixer can't play mp3's

diff --git a/vcmibuilder b/vcmibuilder
--- a/vcmibuilder
+++ b/vcmibuilder
@@ -30,6 +30,7 @@ do
 		--dest) dest_dir=$2         ; shift 2 ;;
 		--wog) wog_archive=$2       ; shift 2 ;;
 		--vcmi) vcmi_archive=$2     ; shift 2 ;;
+		--convertMP3) useffmpeg=true; shift 1 ;;
 		--download) download=true   ; shift 1 ;;
 		--validate) validate=true   ; shift 1 ;;
 		*) print_help=true          ; shift 1 ;;
@@ -57,12 +58,15 @@ then
 	echo " --vcmi ARCHIVE   " "Path to manually downloaded VCMI data package"
 	echo "                  " "Requires unzip"
 	echo
-	echo " --download       " "If specified vcmibuilder will download packages using wget"
+	echo " --convertMP3     " "Convert all mp3 files into ogg/vorbis"
+	echo "                  " "Requires ffmpeg"
+	echo
+	echo " --download       " "Automatically download requied packages using wget"
 	echo "                  " "Requires wget and Internet connection"
 	echo
 	echo " --dest DIRECTORY " "Path where resulting data will be placed. Default is ~/.vcmi"
 	echo
-	echo " --validate       " "If specified vcmibuilder will run basic validness checks"
+	echo " --validate       " "Run basic validness checks"
 	exit 0
 fi
 
@@ -108,6 +112,11 @@ then
 		warning "Warning: Both gog and cd options were specified. cd options will be ignored"
 		unset cd1_dir cd2_dir
 	fi
+fi
+
+if [[ -n "$useffmpeg" ]] 
+then
+	test_utility "ffmpeg" "-version"
 fi
 
 if [[ -n "$cd1_dir" ]] 
@@ -249,6 +258,25 @@ if [[ -n "$vcmi_archive" ]]
 then
 	echo "decompressing $vcmi_archive"
 	unzip -qo "$vcmi_archive" -d "$dest_dir" || fail "Error: failed to extract VCMI archive!"
+fi
+
+if [[ -n "$useffmpeg" ]]
+then
+	# now when all music files (including WoG theme) were installed convert them to ogg
+	echo "Converting mp3 files..."
+
+	OIFS="$IFS"
+	IFS=$'\n' 
+
+	for file in `find "$dest_dir" -type f -name "*.mp3"`
+	do
+		echo "Converting $file"
+		ogg=${file%.*}
+		ffmpeg -y -i "$file" -acodec libvorbis "$ogg".ogg 2>/dev/null || fail "Error: failed to convert $file to ogg/vorbis using ffmpeg" "rm -f "$ogg".ogg"
+		rm -f $file
+	done
+
+	IFS="$OIFS"
 fi
 
 if [[ -n "$validate" ]]
